# Generated by Django 5.0 on 2025-08-08 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainwebsite", "0008_transcribeaccesscode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicLinkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_link_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "unique_together": set(),
                "indexes": [
                    models.Index(
                        fields=["user", "requested_at"],
                        name="mainwebsite_user_id_795a34_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "requested_at"],
                        name="mainwebsite_ip_addr_63d8fd_idx",
                    ),
                    models.Index(
                        fields=["email", "requested_at"],
                        name="mainwebsite_email_f6ae10_idx",
                    ),
                ],
            },
        ),
    ]
