# Generated by Django 3.0.4 on 2021-12-15 20:03

from django.db import migrations, models
import mainwebsite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.CharField(default=mainwebsite.models.unique_short_code, max_length=12, unique=True)),
                ('real_url', models.URLField()),
            ],
        ),
    ]
