# Generated by Django 5.0 on 2025-08-11 03:42

import django.db.models.deletion
import mainwebsite.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en-US", "en-US"),
                            ("es-MX", "es-MX"),
                            ("fr", "fr"),
                            ("vi", "vi"),
                            ("ko", "ko"),
                        ],
                        default="",
                        max_length=5,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShortenedUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shortened_url",
                    models.CharField(
                        default=mainwebsite.models.unique_short_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("real_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="TranscribeAccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_code", models.CharField(max_length=25, unique=True)),
                ("number_of_calls", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PhoneCallSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caller_sid",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("caller_is_active", models.BooleanField(default=False)),
                (
                    "callee_sid",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("callee_is_active", models.BooleanField(default=False)),
                (
                    "callee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="callee",
                        to="mainwebsite.phonenumber",
                    ),
                ),
                (
                    "caller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caller",
                        to="mainwebsite.phonenumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MagicLinkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_link_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "requested_at"],
                        name="mainwebsite_user_id_795a34_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "requested_at"],
                        name="mainwebsite_ip_addr_63d8fd_idx",
                    ),
                    models.Index(
                        fields=["email", "requested_at"],
                        name="mainwebsite_email_f6ae10_idx",
                    ),
                ],
            },
        ),
    ]
