# Generated by Django 4.2.6 on 2023-10-20 16:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0002_alter_shortenedurl_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('language', models.CharField(blank=True, default='', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_is_active', models.BooleanField(default=False)),
                ('callee_is_active', models.BooleanField(default=False)),
                ('callee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callee', to='mainwebsite.phonenumber')),
                ('caller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller', to='mainwebsite.phonenumber')),
            ],
        ),
    ]
