# Generated by Django 4.2.6 on 2023-11-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0003_phonenumber_phonecallsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='language',
            field=models.CharField(blank=True, choices=[('en-us', 'en-us'), ('es-mx', 'es-mx'), ('fr', 'fr'), ('vi', 'vi'), ('ko', 'ko')], default='', max_length=5, null=True),
        ),
    ]
