# Generated by Django 4.2.6 on 2023-11-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0005_phonecallsession_call_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='language',
            field=models.CharField(blank=True, choices=[('en-US', 'en-US'), ('es-MX', 'es-MX'), ('fr', 'fr'), ('vi', 'vi'), ('ko', 'ko')], default='', max_length=5, null=True),
        ),
    ]
